commit_message: '[ci skip] New %language% translation from Crowdin'
append_commit_message: false
files:
  - source: /spyder_reports/locale/spyder_reports.pot
    translation: /spyder_reports/locale/%two_letters_code%/LC_MESSAGES/%file_name%.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
